#!/usr/bin/env bash

# 6-stop_me_if_you_can
process_name="some_process_name"

# Using pgrep to get the PID
pid=$(pgrep "$process_name")

# Check if a PID was found
if [[ -z "$pid" ]]; then
    echo "Process not found"
else
    echo "PID of $process_name: $pid"
fi
