#!/usr/bin/env bash
#6-stop_me_if_you_can
echo "Attempting to stop the '4-to_infinity_and_beyond' process..."

pkill "4-to_infinity_and_beyond"

if [ $? -eq 0 ]; then
    echo "Process '4-to_infinity_and_beyond' found and termination signal sent."
else
    echo "Could not find or terminate process '4-to_infinity_and_beyond'. It might not be running."
fi

echo "Script finished."
