#!/bin/bash

process_name="4-to_infinity_and_beyond"
pid=$(ps aux | grep "$process_name" | grep -v "grep" | awk '{print $2}')

if [ -n "$pid" ]; then
  echo "Terminating process $process_name with PID $pid"
  kill -SIGTERM "$pid"
fi
